"""
ai/models.py — Strongly typed generative data contracts for Explainable AI.

This module defines the Pydantic models that the Gemini LLM is 
strictly forced to output. It ensures the AI produces structured, 
deterministic explanations mapped directly to verified evidence.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Any, Dict
import uuid

from pydantic import BaseModel, Field

# ── Input Models ──────────────────────────────────────────────────────────────

class AIContext(BaseModel):
    """
    The strictly filtered, scrubbed payload handed to the LLM.
    Guarantees no raw HTML, JS, or CSS ever reaches the generative prompt.
    """
    context_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_metadata: Dict[str, str] = Field(default_factory=dict, description="Metadata about the target environment")
    policy_version: str = Field("1.0", description="The active Risk Engine policy version")
    engine_version: str = Field("1.0", description="The active Evidence Engine version")
    
    # We store these as generic Dicts here for serialization flexibility, 
    # but the Context Builder ensures all dangerous fields are purged.
    scrubbed_evidence: Dict[str, Any]
    scrubbed_risk_assessment: Dict[str, Any]


# ── Nested Output Models ──────────────────────────────────────────────────────

class AIMetadata(BaseModel):
    """Transparency tracking for the generative process."""
    model_name: str = Field("gemini-2.5-flash", description="The underlying LLM used")
    temperature: float = Field(0.2, description="The deterministic temperature setting")
    prompt_version: str = Field("1.1", description="Version of the prompt templates used")
    policy_version: str = Field("1.0", description="Version of the risk policy used")
    generated_at: datetime = Field(default_factory=datetime.utcnow, description="UTC time of generation")


class ExecutiveSummary(BaseModel):
    """High-level AI narrative intended for C-Suite or non-technical readers."""
    summary_text: str = Field(..., description="2-3 paragraphs explaining the security posture")
    primary_threat_vector: str = Field(..., description="The most significant attack path identified")
    business_impact: str = Field(..., description="How this affects the business/brand/users")


class EvidenceReference(BaseModel):
    """Explicit citation linking the AI's claim to a deterministic fact."""
    evidence_id: str = Field(..., description="The ID of the raw evidence artifact")
    finding_id: str = Field(..., description="The ID of the finding from the Risk Engine")
    source_module: str = Field(..., description="The Evidence Engine module that collected this (e.g., 'ssl_checker')")
    timestamp: str = Field(..., description="When the evidence was collected")
    confidence: int = Field(..., description="The Risk Engine's confidence in this specific evidence (0-100)")


class VerificationChecklist(BaseModel):
    """Actionable steps a developer can take to verify the fix."""
    checklist_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    finding_id: str = Field(..., description="The finding this checklist verifies")
    steps: List[str] = Field(
        ..., 
        description="Sequential verification steps (e.g., ['Add CSP Header', 'Restart Server', 'Run Scan'])"
    )


class Recommendation(BaseModel):
    """Structured remediation advice tailored to developers."""
    recommendation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    finding_id: str = Field(..., description="The finding this recommendation remediates")
    priority: str = Field(..., description="Critical, High, Medium, Low")
    estimated_fix_time: str = Field(..., description="e.g., '5 min', '2 hours', '1 sprint'")
    difficulty: str = Field(..., description="Easy, Moderate, Hard")
    affected_component: str = Field(..., description="e.g., 'Nginx Config', 'React Frontend'")
    recommended_fix: str = Field(..., description="Clear, actionable instruction on how to remediate")
    example_configuration: str = Field(..., description="Code snippet demonstrating the fix")
    reference_links: List[str] = Field(default_factory=list, description="URLs to official documentation")


class FindingExplanation(BaseModel):
    """
    Comprehensive, structured narrative generated by the AI for a single finding.
    It MUST cite the evidence used.
    """
    explanation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    finding_id: str = Field(..., description="Link back to the deterministic finding")
    finding_title: str = Field(..., description="The title of the original finding")
    reasoning_confidence: int = Field(..., description="The LLM's confidence (0-100) in this specific reasoning chain")
    
    reason: str = Field(..., description="A concise 1-sentence summary of why this is a problem")
    technical_explanation: str = Field(..., description="Deep dive into the mechanics of the vulnerability")
    developer_explanation: str = Field(..., description="Explanation tailored for a developer building the app")


# ── Root Output Model ─────────────────────────────────────────────────────────

class ExplainabilityReport(BaseModel):
    """
    The final, structured output forced upon the Gemini API.
    Splits the narrative into distinct, composable domains.
    """
    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    assessment_reference_id: str = Field(..., description="The ID of the RiskAssessment this report explains")
    
    metadata: AIMetadata = Field(default_factory=AIMetadata)
    executive_summary: ExecutiveSummary
    explanations: List[FindingExplanation] = Field(default_factory=list)
    recommendations: List[Recommendation] = Field(default_factory=list)
    verification_checklists: List[VerificationChecklist] = Field(default_factory=list)
    evidence_references: List[EvidenceReference] = Field(default_factory=list)

    class Config:
        extra = "forbid"
